##############################################################
# Language                                                   #
##############################################################
# language: 现在在使用的语言
# default: 正在使用的语言中不包含的词汇，转而使用默认语言代替
language: Simplified Chinese
default_language: Simplified Chinese

##############################################################
# Style                                                      #
##############################################################
# theme: 当前使用的编辑器配色主题
# default_theme: 当前使用的编辑器配色主题不包含的配色方案，使用默认配色主题
# transparentcolor: 被识别为透明的颜色列表
theme: default
default_theme: default
transparentcolor:
  - #361599